### ISSUE TITLE
pre-commit output disappear after running by ctrl + shift + p 

### ISSUE THREAD

**Issue by rafiahmad16** [magicmark/pre-commit-vscode#190]
Whenever I try to run any hook or all hooks from ctrl + shift + p and search from `pre-commit run` the output shown in the new bash screen in same terminal and then it closes automatically and getting the below error:
`The terminal process "/home/rafi/Documents/ia-projects/project/venv/bin/pre-commit 'run', 'null', '--files', '/home/rafi/Documents/ia-projects/project/apps/download/tests/test_payload_validation.py'" failed to launch (exit code: 1).`

**Comment by magicmark** [comment]
https://github.com/magicmark/pre-commit-vscode/releases/tag/v0.1.0

the terminal window now stays open for a non-0 exit code. please reopen if this is still an issue.
