### ISSUE TITLE
Publish extension to OpenVSX Marketplace 

### ISSUE THREAD

**Issue by trinitronx** [magicmark/pre-commit-vscode#193]
In the past few years, many OSS Linux packagers of VSCode, VSCodium, (a.k.a. Code OSS) have moved to using [OpenVSX extension Registry][openvsx] and had to [disable Microsoft's Extensions Marketplace by default][1] due to Microsoft's licensing restrictions.

So, in order for most Linux developers using stock OSS-packaged versions of VSCode to find extensions such as this one, it's important to also publish to OpenVSX.

[1]: https://www.reddit.com/r/vscode/comments/kb0eb5/extensions_missing/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1
[openvsx]: https://open-vsx.org/

**Comment by magicmark** [comment]
https://open-vsx.org/extension/MarkLarah/pre-commit-vscode

thanks for the heads up!
