### ISSUE TITLE
Use pre-commit from virtualenv

### ISSUE THREAD

**Issue by TheButlah** [magicmark/pre-commit-vscode#46]
Would it be possible to hook into vscode's venv detection to check for pre-commit in the current virtualenv? We include pre-commit as part of our development dependencies, so it gets installed into a virtualenv located at the project root.

**Comment by magicmark** [comment]
@TheButlah yea, we do this pretty naively right now:

https://github.com/magicmark/pre-commit-vscode/blob/1f199598a72ef819f964321a4502978aeaa136f9/src/index.js#L33:L51

I looked into this here https://github.com/magicmark/pre-commit-vscode/pull/4, but haven't had chance to pick this back yet

**Comment by TheButlah** [comment]
Since there are a number of places the virtualenv could be (in my case, `.venv`), maybe using the venv location detected by the Microsoft extension would be best? It's defined at `python.pythonPath` (see [here](https://github.com/TheButlah/vscode-reorder-python-imports/blob/a42f6f18459d68034dfce1900ab3811048ab5c93/src/reorderImportsProvider.ts#L62) for an example). Then the git hook and PATH can be used as fallbacks.

**Comment by ben-uptycs** [comment]
Is there an update on this? This extension will not work for me at all as is because my Poetry virtualenvs always live at `.venv`. VSCode just complains `Could not find an installed version of pre-commit!`. I think @TheButlah is right in that using the venv location detected by the Microsoft extension would be a great fix.

**Comment by hege-aliz** [comment]
Same issue with pipenv... Is there a plan to fix this, should we count with it?

**Comment by magicmark** [comment]
https://github.com/magicmark/pre-commit-vscode/releases/tag/v0.1.0

I've added the suggested logic - please reopen if this is still an issue (maybe there's more locations to search)
